language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
  - "pypy3"
jobs:
  allow_failures:
    - python: "nightly"

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run mamba
after_success:
  - pipenv run coverage report
